### ISSUE TITLE
Configurable way do define default sort order for collections

### ISSUE THREAD

**Issue by goodtouch** [jekyll/jekyll#3720]
In order to :
- help reduce the gap between document collections and posts (#3169 and #3690)
- help fixing #3539
- port #670 for collection (:grin:)

I started working on configurable way to define default sort order for collections in the metadata
(thus allowing to sort collections by reverse date provided that the documents store a date field in the data Hash).

I used the following `SQL/Rails` syntax in `_config.yml` :

```yaml
my_date_sorted_collection:
  output: true
  order: date DESC, slug
```

The string format supports multiple comma separated properties and nested fields (`time.start ASC`) (with limit to prevent abuse).

## Implementation

I created a `Jekyll::Sorter` module with an `order` method.

It returns and caches a `lambda` that can be used with the `Enumerable#sort` method. ie:

```ruby
document_array.sort(&:Jekyll::Sorter.order('date DESC, slug'))
```

I made Post and Collection use this instead of the default `sort!` + `<=>` methods.

The properties are fetched from the data attribute of the object elements in the array.

## WIP

Not enough to start a PR, but it should be a nice starting point for a discussion.

You can:
- check out progresses [here](https://github.com/goodtouch/jekyll/tree/add-configuration-for-collection-order)
- or quick-start a blog with a vendored gem using this branch for those who want to test & hack things:

(OMG I should have done this a long time ago!)

```
git clone --branch add-configuration-for-collection-order https://github.com/goodtouch/jekyll-dev-blog.git
cd jekyll-dev-blog
./script/bootstrap
./script/server
```

## To-do list:

- [X] Add Jekyll::Sorter module implementing the `order` method
- [X] Support nested fields (`{'time' => {'start' => 'whatever'}}`, Jekyll::Sorter.order("time.start ASC"))
- [X] Validate format of the order string
- [X] Limit nesting level (2) and number of fields (2) to prevent GitHub Page potential abuses (easy to change constants)
- [ ] Gracefully handle nil fields
- [X] Make Posts and Collections use the same Jekyll::Sorter.order (with different default arguments) when populating liquid hashes
- [X] in-code documentation
- [X] add a jekyll filter (temporarily named order for now as it's not backward compatible with the sort filter)
      this one should fix #3539 if using order: 'time.start' instead of sort
- [ ] add doc in site/_docs
- [ ] add some tests
- [X] add some benchs

**Comment by envygeeks** [comment]
I would personally like to see performance tests come with this, because that "SQL/Rails" syntax (which SQL isn't anything to do with Rails) would considerably slow down things, when you have to parse each and every run and this is an exponential issue.

**Comment by goodtouch** [comment]
SQL was for the format of the string and Rails for the `order` method.

I added a `@sorters[args] ||= lambda...` to prevent parsing the formatted string every time

I'm planning to test the existence at the beginning of the method but didn't do it yet (I need to replace the in_place `map!` and `split` on the args, but I wanted to get a working prototype and talk about the idea & implementation & method names before focusing on optimisation...)

**Comment by goodtouch** [comment]
I can also add a 'native fallback' when sorting posts by date and collection by path so that it won't slow things down if not using a custom order.

**Comment by goodtouch** [comment]
Here is an extract of some benchmarks for the sorting method with various options :
(full details at [goodtouch/sorter-bench](https://github.com/goodtouch/sorter-bench))

## Big Array (1 x 100_000 elements)

```sh
                                                user     system      total        real
jekyll                                      0.110000   0.000000   0.110000 (  0.104057)
sorter lambda w/o cache w/o nesting         0.140000   0.000000   0.140000 (  0.150984)
sorter lambda w/ cache w/o nesting          0.150000   0.000000   0.150000 (  0.152537)
sorter lambda w/o cache w/ nesting          0.490000   0.000000   0.490000 (  0.492966)
sorter lambda w/ cache w/ nesting           0.480000   0.000000   0.480000 (  0.498932)
sorter class eval w/ cache (w/ nesting)     0.060000   0.000000   0.060000 (  0.067487)
```

## Small Arrays (1_000 x 100 elements)

```sh
                                                user     system      total        real
jekyll                                      0.110000   0.000000   0.110000 (  0.111950)
sorter lambda w/o cache w/o nesting         0.190000   0.000000   0.190000 (  0.185490)
sorter lambda w/ cache w/o nesting          0.160000   0.000000   0.160000 (  0.165312)
sorter lambda w/o cache w/ nesting          0.530000   0.000000   0.530000 (  0.533625)
sorter lambda w/ cache w/ nesting           0.510000   0.000000   0.510000 (  0.516132)
sorter class eval w/ cache (w/ nesting)     0.070000   0.000000   0.070000 (  0.077700)
```

It seems like :
- Using block, lambda or proc doesn't make much difference (I removed them here, see [goodtouch/sorter-bench](https://github.com/goodtouch/sorter-bench) for details)
- Main source of latency comes from accessing nested elements in the hash (~x5)
- If we don't use nesting, the impact is pretty low (< x2).
- Cached string manipulation have a small impact (see Small Arrays)
- The overall is still quite good considering we are sorting 100_000 Elements on an Core 2 Duo laptop.
- In case it's an issue for GitHub Pages, I also added a dynamic `class_eval` sorter that provides the same performance as the current Jekyll sorting method, with caching (so that we don't class eval every time), inline nested access to the data hash, and quite easy to secure against potential user input security concerns (see `Sorter#ce_order`)
