### ISSUE TITLE
Release Jekyll v3.2

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4891]
This is a checklist for releasing v3.2.0.

- [x] Documentation for gem-based themes
- [x] Write `jekyll new-theme` command ( #4848 )
- [x] Port changes from #4911 forward to `master` branch.
- [x] Fix `jekyll new-theme` and theme template based on feedback ( #5042 )
- [x] Convert Jekyll-new theme to a gem-based theme ( #4922 )
- [x] Cull list of issues in the milestone & punt where possible
- [x] Test Jekyll against Pathutil to find breakage.
- [x] ThemeBuilder: Remove example site from theme (#5141)
- [x] Release 1.0 of `minima` (https://github.com/jekyll/minima/issues/1)
- [x] Publish release post ( #5140 )
- [x] Release `jekyll` gem
- [x] Release `jekyll-docs` for v3.2.0

/cc @jekyll/stability @jekyll/build @jekyll/ecosystem

**Comment by envygeeks** [comment]
Add `Pathutil#cleanpath` to that list because we have `Pathutil` in there now and I need to make sure it's completely backwards compatible.

**Comment by benbalter** [comment]
> Documentation for gem-based themes

https://jekyllrb.com/docs/themes/

**Comment by parkr** [comment]
> https://jekyllrb.com/docs/themes/

HOW DID THAT GET THERE?!

**Comment by envygeeks** [comment]
@parkr @benbalter that's why I commented that the release of the documentation is part of a much larger issue, every time we update the site the beta documentation lands on there indiscriminately and it's led to quite a few people asking questions about unreleased features and being confused.

**Comment by benbalter** [comment]
> HOW DID THAT GET THERE?! 

[I wrote them!](https://github.com/jekyll/jekyll/issues/4595)

**Comment by chrisfinazzo** [comment]
In cases like this, would it be preferable to ask that changes to documentation land in a separate branch? Currently, everything goes straight to master and sometimes things aren't ready. Whether it gets tagged as beta, or something like `{{feature}}-docs-vx` where `vx` is the anticipated milestone for when it should be integrated.

This is probably too formal, curious to hear what @jekyll/documentation thinks.

**Comment by envygeeks** [comment]
That's actually along the lines almost of what I was thinking.  I was thinking that I could talk to @parkr about maybe adjusting the merge bot so he can add an extra flag to merge documentation into the latest stable branch and only release the latest stable branch onto the site, and then we could adjust the domain to do something like beta.jekyllrb.com for master (of which I would happily host if Github Pages can't work that way.)

**Comment by erlend-sh** [comment]
I like how Ionic has implemented versioned docs in their Jekyll site:

http://ionicframework.com/docs/api/service/$ionicBackdrop/

I can see something like that working very well for jekyllrb.com as well, tough for Jekyll differentiating between "stable" and "beta" (or latest/nightly/dev etc) would probably suffice.

**Comment by envygeeks** [comment]
@erlend-sh I always liked doing it that way but that might take a ticket of it's own to deal with as it's a decent sized job and would require some restructuring and optimization.  I wonder if we couldn't also add documentation via Cucumber.io doesn't it do that same style documentation except through our cucumber files?

**Comment by chrisfinazzo** [comment]
Has anyone pulled the default theme out to create a gem yet? If not, I'm game.

**Comment by tentakel** [comment]
@chrisfinazzo ~~hi game, i'm dad~~ sure, go ahead

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by chrisfinazzo** [comment]
@jekyll/core Still WIP - need to figure out Rubocop errors - but it's a [starting point][]

[starting point]: https://github.com/chrisfinazzo/jekyll-new

**Comment by parkr** [comment]
@chrisfinazzo I already did most of this! Sorry :/ I forgot to make the repo public.

**Comment by chrisfinazzo** [comment]
Ack! Please push it when you're ready.

I want to do a separate gem for my own site (currently working through the nuances of [Susy][] grids), so this wasn't a bad use of 20 minutes

👋🏻 to @zellwk, his book is a great way to get started with it. 

[Susy]: https://github.com/oddbird/susy

**Comment by parkr** [comment]
@chrisfinazzo I have the beginnings of it over here: https://github.com/jekyll/minima Finishing up in #4922.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least
one month.

The resources of the Jekyll team are limited, and so we are asking for your help.

If you can still reproduce this error on the <code>3.1-stable</code> or <code>master</code> branch,
please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider building it first as a plugin. Jekyll 3 introduced
[hooks](http://jekyllrb.com/docs/plugins/#hooks) which provide convenient access points throughout
the Jekyll build pipeline whereby most needs can be fulfilled. If this is something that cannot be
built as a plugin, then please provide more information about why in order to keep this issue open.

Thank you for all your contributions.

**Comment by envygeeks** [comment]
Wrong ticket bud.

**Comment by parkr** [comment]
Merged the last PR for theme stuff.. Off to the races. Going to cull the milestone by this weekend and get this shipped!

**Comment by parkr** [comment]
Thinking through some last-minute things here:

- Should we upgrade to Rouge 2?
- Should we upgrade to Liquid 4?

Releasing another beta now.

**Comment by vaughandroid** [comment]
@parkr I don't know about those specific libraries, or how good your test coverage is, but in my experience upgrading libraries is best done at the start of a release cycle, not the end. Too much risk!

**Comment by AndorChen** [comment]
Yeah, Rouge 2 changes a lot, but it has [a backwards-compatibility solution](https://github.com/jneen/rouge/blob/master/lib/rouge/formatters/html_legacy.rb).

**Comment by budparr** [comment]
@parkr Aside from any other considerations, but I think there are performance gains in Liquid 4 that would be welcome, and from this conversation it doesn't seem as though it would be a difficult change: https://github.com/Shopify/liquid/issues/678

**Comment by benbalter** [comment]
> Should we upgrade to Rouge 2? Should we upgrade to Liquid 4?

I'm a big proponent of getting 3.2 out the door with its current scope, and then immediately scoping a small 3.3 if we're interested in those major bumps. Minor releases are cheap and we're not on a set schedule, so no harm in getting 3.3 out a month (or less) after 3.2. Fewer moving parts means fewer things that can break.

**Comment by spudowiar** [comment]
Agree with @benbalter, if/when Rouge 2 and Liquid 4 start causing issues, people will still be able to use all the features of Jekyll 3.2 by not using Jekyll 3.3.

**Comment by parkr** [comment]
Thanks for the feedback! Seems small enough to do for a minor release, but should be done for 3.3, not 3.2. 😄

**Comment by dalanmiller** [comment]
@parkr I'd love to see Rouge 2 because our site uses a lot of Javascript template strings which weren't fixed until recently.

**Comment by parkr** [comment]
@dalanmiller We're going to have to punt on Rouge 2 until Jekyll 3.3. Too many moving parts. (Integrates into `{% highlight %}` and into kramdown, so both need to be compatible.)

**Comment by parkr** [comment]
Done!!!!!! 🎉 🎊
