### ISSUE TITLE
Release v3.2.1

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5159]
Just going through the issues from yesterday's release. Glad everyone is upgrading! I want to get a v3.2.1 out ASAP, probably Monday as I'm traveling this weekend.

- [x] Fix theme generator so theme files are _included_ rather than rejected :facepalm: (#5152)
- [x] Fix rejection of symlinked themes (e.g. with a Homebrewed installation of Ruby) (#5156)
- [x] Fix Windows compatibility (#5146)
- [x] Release post
- [x] Update history, bump version, tag it & release gem

**Comment by jleclanche** [comment]
So you know, your 3.2.0 release is not showing up in Releases:

https://github.com/jekyll/jekyll/releases

It's only in tags, marking the latest release as 3.1.6 on github.

**Comment by parkr** [comment]
Fixes #4677.

**Comment by parkr** [comment]
Released. http://jekyllrb.com/news/2016/08/02/jekyll-3-2-1-released/
