### ISSUE TITLE
Jekyll 3.3 Release Gameplan

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5400]
Hey y'all, looking to release 3.3 soon. 3.2.2 is no longer slated for release as we have a number of things on `master` that we can't release in a PATCH release per SemVer. My goal is to get 3.3 out next week.

Some things left to do:

- [x] Go through milestone and punt on issues we don't need
- [x] Add `absolute_url` and `relative_url` filters for easier site & theme development (#5399, #5405)
- [x] Site template: remove `index.html` custom code and replace with `home.html` layout in minima (https://github.com/jekyll/minima/pull/48 and #5420)
- [x] Site template: remove `css/main.scss` custom code and replace with `assets/main.scss` asset in minima (https://github.com/jekyll/minima/pull/43)
- [x] Release minima v2
- [x] Site template: remove `example.com` from config, move to a comment. (#5338)
- [x] `jekyll serve` should set `site.url` to `http://localhost:4000` when `JEKYLL_ENV=development` (#5431)
- [x] Fix theme issue on Windows (#5256)
- [x] Release post (#5442)

/cc @benbalter

**Comment by ashmaroli** [comment]
> Site template: remove example.com from config, move to a comment.

**[PR-5338](https://github.com/jekyll/jekyll/pull/5338):** **set empty url in config file by default**

**Comment by ashmaroli** [comment]
> Site template: remove index.html custom code and replace with home.html layout in minima
> Site template: remove css/main.scss custom code and replace with assets/main.scss asset in minima

Unless we release an update concurrently, for both Jekyll & Minima, its going to create further confusion, just like how another recent breaking change on minima had caused.

**Comment by ashmaroli** [comment]
Please raise the Priority for issue-5192 (and its assoc. PR) as its of equal concern (for Windows Users) to the breaking change issue related to `url: http://www.example.com`

**Comment by parkr** [comment]
@ashmaroli The associated PR for #5192 is unfortunately failing in both the tests that were added. Would you be willing to take a crack at fixing it?

**Comment by parkr** [comment]
> Site template: remove index.html custom code and replace with home.html layout in minima
> Site template: remove css/main.scss custom code and replace with assets/main.scss asset in minima

@ashmaroli Yeah, I was going to release this as `minima` `v2.0`.

**Comment by ashmaroli** [comment]
> Would you be willing to take a crack at fixing it?

I'll make an attempt.

**Comment by ashmaroli** [comment]
Also I think the `jekyll new` template dir should be modified to have it automatically conform to our new added support for `assets/` but I havent fully understood the new feature to create a pull..

**Comment by ashmaroli** [comment]
> Site template: remove `css/main.scss` custom code and replace with `assets/main.scss` asset in minima

Ref: #5402, jekyll/minima#43
moving `css/main.scss` to `assets/css/main.scss` in minima instead..

**Comment by ashmaroli** [comment]
> Site template: remove `index.html` custom code and replace with `home.html` layout in minima

Ref: #5420

**Comment by Crunch09** [comment]
> jekyll serve should set site.url to http://localhost:4000 when JEKYLL_ENV=development

#5431

**Comment by parkr** [comment]
Getting close! Just released an RC1. Planning on releasing v3.3 tomorrow morning `America/Los_Angeles` time.

**Comment by ashmaroli** [comment]
> Just released an RC1

Great!! Testing it out locally produced an error ( as expected.. since minima 2.0 has not been shipped yet ):
```
jekyll new test_blog
cd test_blog
bundle exec jekyll s
[...]
            Source: C:/Sites/Jekyll Sites/TEST
       Destination: C:/Sites/Jekyll Sites/TEST/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'home' requested in index.md does not exist.
                    done in 0.78 seconds.
[...]
```
As expected, `http://localhost:4000/` shows a blank page

**Comment by DirtyF** [comment]
@ashmaroli works perfectly fine if you use github source in your Gemfile.

**Comment by ashmaroli** [comment]
yes I know.. hence mentioned *as expected* and did not open a dedicated ticket..

**Comment by parkr** [comment]
https://rubygems.org/gems/jekyll/versions/3.3.0 🎉
