### ISSUE TITLE
Release v3.5.2

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#6292]
I'd like to release a PATCH release, v3.5.2, while we work on v3.6.0. It will include:

- [x] #6288: Backport #6281 for v3.5.x: Fix Drop#key? so it can handle a nil argument
- [x]  #6287: Backport #6280 for v3.5.x: Guard against type error in absolute url
- [x] #6301: Backport #6266 for v3.5.x: Memoize the return value of Document#url
- [x] #6302: Backport #6273 for v3.5.x: delegate `StaticFile#to_json` to `StaticFile#to_liquid`
- [x] #6304: Backport #6226 for v3.5.x: `Reader#read_directories`: guard against an entry not being a directory
- [x] #6303: Backport #6247 for v3.5.x: kramdown: symbolize keys in-place

Anything else (small, bug fixes only) you'd like to see included?

/cc @jekyll/affinity-team-captains

**Comment by DirtyF** [comment]
@parkr fine by me 👍

**Comment by mattr-** [comment]
If there's nothing else to add to the release, then I say go for it. :100:

**Comment by parkr** [comment]
Well there might be. I could do them in a v3.5.3, or here. I'm considering:

  * `Reader#read_directories`: guard against an entry not being a directory (#6226)
  * kramdown: symbolize keys in-place (#6247)
  * Memoize the return value of Document#url (#6266)
  * delegate `StaticFile#to_json` to `StaticFile#to_liquid` (#6273)

**Comment by pup** [comment]
isnt #6266 a pretty significant performance boost? let's get at least that in

**Comment by parkr** [comment]
> isnt #6266 a pretty significant performance boost? let's get at least that in

Yeah, it is! I'll submit a PR to get that in.

**Comment by parkr** [comment]
May as well just do 'em all.

**Comment by parkr** [comment]
All tests pass! Releasing...

**Comment by parkr** [comment]
Released! I'll get a blog post up momentarily.

**Comment by parkr** [comment]
http://jekyllrb.com/news/2017/08/12/jekyll-3-5-2-released/

**Comment by DirtyF** [comment]
@parkr I just noticed @jekyllbot didn't create the release on GitHub, so I manually added it: https://github.com/jekyll/jekyll/releases

**Comment by parkr** [comment]
Oh, weird! Thanks, @DirtyF!
