### ISSUE TITLE
Release Jekyll v3.6.0

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#6314]
Hey, @jekyll/affinity-team-captains! Let's make a plan to release v3.6.0.

This release, I'd like to focus on adding Rouge 2 compatibility. All the bugfixes in this release are part of v3.5.2 so it's just the minor enhancements that are important here.

- [x] https://github.com/jekyll/jekyll/pull/5919: Add shim that works for both Rouge 1 and Rouge 2

Then we have the following in the milestone. What should we punt on?

- [x] #6130: Update dependency constraint to allow for rouge v2.1.0
- [ ] #6060: jekyll serve --source constructs wrong paths when pwd is another Jekyll tree
- [ ] #5904: Sort collection items by an attribute.
- [ ] #5181: "Liquid Exception: invalid byte sequence in UTF-8..." with binaries
- [ ] #2853: Jekyll fails if markdown contains UTF-8 Byte Order Marker
- [ ] #2518: Setting Collections Relative Directory: Right Approach?

I'd like to ship this update by September 1 at the latest.

**Comment by parkr** [comment]
Additionally, given the Rouge 2 compatibility, I'd like to *also* release at least one release candidate so people have a chance to test it out for us and find bugs.

**Comment by ashmaroli** [comment]
#5904 is awaiting a review.

**Comment by mattr-** [comment]
I'd like to punt on #6060 for this release. I just read the issue about an
hour ago and am still trying to get back into a cadence with my open source
contributions.

**Comment by parkr** [comment]
@ashmaroli Great!

@mattr- Any objection to me submitting a PR for that and merging for this release? Targeting September 1 for the final release so we have time. :)

**Comment by mattr-** [comment]
@parkr If you have something already, go for it. :smiley:

**Comment by ashmaroli** [comment]
@parkr any word regarding #5904 ..?

**Comment by ccamacho** [comment]
#2518 +1

**Comment by parkr** [comment]
I'm going to punt on anything that isn't already merged and get this release out.

**Comment by ashmaroli** [comment]
PR to consider : #6182

**Comment by parkr** [comment]
Shipped!

**Comment by parkr** [comment]
https://jekyllrb.com/news/2017/09/21/jekyll-3-6-0-released/
