### ISSUE TITLE
Tracking: Release Jekyll v3.9.1

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#8634]
Tracking issue for releasing v3.9.1.

- [x] Upstream (master) PR: https://github.com/jekyll/jekyll/pull/8618
- [x] 3.9-stable PR: https://github.com/jekyll/jekyll/pull/8629
- [x] 3.9-stable Docs/Release post PR: https://github.com/jekyll/jekyll/pull/8631
- [x] Release gem! https://rubygems.org/gems/jekyll/versions/3.9.1
- [x] Ensure tag & release notes are pushed to GitHub https://github.com/jekyll/jekyll/releases/tag/v3.9.1
- [x] Upstream Docs/Release post PR: https://github.com/jekyll/jekyll/pull/8635
